import os
import sys
import pandas as pd
import smtplib
from email.mime.text import MIMEText
from email.header import Header
from datetime import datetime

# =========================
# Project Root Directory
# =========================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)

from scripts.logger_setup import setup_logger
from config.config import (
    SMTP_SERVER,
    SMTP_PORT,
    EMAIL_SENDER,
    EMAIL_PASSWORD,
    EMAIL_RECEIVER
)

logger = setup_logger()


# =========================
# Build Email Body
# =========================
def build_email_body(df: pd.DataFrame) -> str:

    today = datetime.now().strftime("%Y-%m-%d")

    if df.empty:
        return f"""Daily Literature Report ({today})

The system completed today's run, but no highly relevant papers were found.

Possible reasons:
1. Search keywords may be too narrow
2. AI filtering criteria may be too strict
3. Few relevant papers were published today
"""

    lines = [
        f"Daily Literature Report ({today})",
        "",
        f"{len(df)} relevant papers were identified today.",
        ""
    ]

    top_n = min(len(df), 10)

    lines.append(f"Top {top_n} Recommended Papers:")
    lines.append("")

    for i, (_, row) in enumerate(df.head(10).iterrows(), start=1):

        title = str(row.get("title", ""))
        year = str(row.get("year", ""))
        journal = str(row.get("journal", ""))
        doi = str(row.get("doi", ""))
        score = str(row.get("score", ""))
        reason = str(row.get("reason", ""))

        lines.append(f"{i}. {title}")
        lines.append(f"   Year: {year}")
        lines.append(f"   Journal: {journal}")
        lines.append(f"   Score: {score}")

        if doi and doi != "nan":
            lines.append(f"   DOI: {doi}")

        if reason and reason != "nan":
            lines.append(f"   AI Reason: {reason}")

        lines.append("")

    lines.append("This email was automatically generated by the AI Literature Monitoring System.")

    return "\n".join(lines)


# =========================
# Main Function
# =========================
def main():

    input_path = os.path.join(BASE_DIR, "outputs", "papers_filtered.csv")

    if not os.path.exists(input_path):

        print("papers_filtered.csv not found. Please run the AI filtering script first.")

        return

    try:

        df = pd.read_csv(input_path)

        # Sort by AI score if available
        if not df.empty and "score" in df.columns:
            df = df.sort_values(by="score", ascending=False)

        body = build_email_body(df)

        subject = f"AI Literature Report | {datetime.now().strftime('%Y-%m-%d')}"

        msg = MIMEText(body, "plain", "utf-8")
        msg["Subject"] = Header(subject, "utf-8")
        msg["From"] = EMAIL_SENDER
        msg["To"] = EMAIL_RECEIVER

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)

        server.starttls()

        server.login(EMAIL_SENDER, EMAIL_PASSWORD)

        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, msg.as_string())

        server.quit()

        logger.info("Daily literature report email sent successfully.")

        print("Daily report email sent successfully.")

    except Exception as e:

        logger.error(f"Failed to send daily report email: {e}")

        print("Failed to send daily report email:", e)


if __name__ == "__main__":
    main()